# Generated by Django 5.2.8 on 2026-01-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sipuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipuser',
            name='secret',
            field=models.CharField(max_length=255),
        ),
    ]
