# Generated by Django 5.2.8 on 2026-02-02 18:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_created_at_company_email_company_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=20)),
                ('callee', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('rate_per_minute', models.DecimalField(decimal_places=4, default=Decimal('0.02'), max_digits=6)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_call_logs', to='accounts.company')),
            ],
        ),
    ]
