# Generated by Django 5.2.8 on 2026-02-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_calllog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallLog',
        ),
    ]
