# Generated by Django 5.2.8 on 2026-02-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
