# Generated by Django 5.2.8 on 2026-02-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_low_balance_threshold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SIPUser',
        ),
    ]
