# Generated by Django 5.2.8 on 2026-02-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_sipuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
