# Generated by Django 5.2.8 on 2026-02-25 09:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rate_per_minute',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=6),
        ),
    ]
