# Generated by Django 5.2.8 on 2026-02-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipuser',
            name='secret',
        ),
    ]
