# Generated by Django 5.2.8 on 2026-02-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0002_remove_sipuser_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipuser',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
