# Generated by Django 5.2.8 on 2026-02-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0003_sipuser_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipuser',
            name='secret',
            field=models.CharField(default='defaultsecret', max_length=128),
            preserve_default=False,
        ),
    ]
