# Generated by Django 5.2.8 on 2026-02-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_calllog'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_call_logs', to='accounts.company'),
        ),
    ]
