# Generated by Django 5.2.8 on 2026-02-02 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_calllog'),
        ('stats', '0002_alter_calllog_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
