# Generated by Django 5.2.8 on 2026-02-02 18:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_calllog'),
        ('stats', '0003_calllog_cost_alter_calllog_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='rate_per_minute',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.02'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_call_logs', to='accounts.company'),
        ),
    ]
