# Generated by Django 5.2.8 on 2026-02-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_calllog'),
        ('stats', '0004_calllog_rate_per_minute_alter_calllog_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='accounts.company'),
        ),
    ]
