# Generated by Django 5.2.8 on 2026-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_calllog_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
