# Generated by Django 5.2.8 on 2026-02-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0003_sipuser_secret'),
        ('stats', '0006_calllog_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='sip_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='sip.sipuser'),
        ),
    ]
